-----------------------------------------------------------
-- Weapons -- Black Market Dealer
-----------------------------------------------------------
weapons_BlackMarket_Dealer = {
    -- Raiding Tools
    [1] = { name = "Noob Lockpick", model = "models/weapons/w_crowbar.mdl", entity = "lockpick_noob", pricesep = 2500, category = "Raiding Tools" },
    [2] = { name = "Keypad Cracker - Noob", model = "models/weapons/w_c4_planted.mdl", entity = "keypad_cracker_noob", pricesep = 4000, category = "Raiding Tools" },
    [3] = { name = "Pro Lockpick", model = "models/weapons/w_crowbar.mdl", entity = "lockpick_pro", pricesep = 4500, category = "Raiding Tools" },
    [4] = { name = "Deployable Keypad Cracker", model = "models/weapons/w_c4_planted.mdl", entity = "weapon_sh_keypadcracker_deploy", pricesep = 6000, category = "Raiding Tools" },
    [5] = { name = "Elite Lockpick", model = "models/weapons/w_crowbar.mdl", entity = "lockpick_elite", pricesep = 6500, category = "Raiding Tools" },
    [6] = { name = "Keypad Cracker - Pro", model = "models/weapons/w_c4_planted.mdl", entity = "keypad_cracker_pro", pricesep = 7000, category = "Raiding Tools" },
    [7] = { name = "Keypad Cracker - Elite", model = "models/weapons/w_c4_planted.mdl", entity = "keypad_cracker_elite", pricesep = 10000, category = "Raiding Tools" },
    [8] = { name = "Breaching Charge", model = "models/weapons/w_c4_planted.mdl", entity = "weapon_sh_doorcharge", pricesep = 25000, category = "Raiding Tools" },
    -- Pistols
    [9] = { name = "M29 Satan", model = "models/weapons/w_m29_satan.mdl", entity = "m9k_m29satan", pricesep = 10000, category = "Pistols" },
    [10] = { name = "Raging Bull", model = "models/weapons/w_taurus_raging_bull.mdl", entity = "m9k_ragingbull", pricesep = 10000, category = "Pistols" },
    [11] = { name = "Raging Bull Scoped", model = "models/weapons/w_raging_bull_scoped.mdl", entity = "m9k_scoped_taurus", pricesep = 11000, category = "Pistols" },
    -- Shotguns
    [12] = { name = "Striker 12", model = "models/weapons/w_striker_12g.mdl", entity = "m9k_striker12", pricesep = 10000, category = "Shotguns" },
    [13] = { name = "USAS", model = "models/weapons/w_usas_12.mdl", entity = "m9k_usas", pricesep = 10000, category = "Shotguns" },
    -- LMGs
    [14] = { name = "PKM", model = "models/weapons/w_mach_russ_pkm.mdl", entity = "m9k_pkm", pricesep = 25000, category = "Light-Machine Guns" },
    [15] = { name = "Ares Strike", model = "models/weapons/w_ares_shrike.mdl", entity = "m9k_ares_shrike", pricesep = 25000, category = "Light-Machine Guns" },
    [16] = { name = "M249 LMG", model = "models/weapons/w_m249_machine_gun.mdl", entity = "m9k_m249lmg", pricesep = 25000, category = "Light-Machine Guns" },
    [17] = { name = "Minigun", model = "models/weapons/w_m134_minigun.mdl", entity = "m9k_minigun", pricesep = 30000, category = "Light-Machine Guns" },
    -- Sniper Rifles
    [18] = { name = "Dragunov SVU", model = "models/weapons/w_dragunov_svu.mdl", entity = "m9k_svu", pricesep = 20000, category = "Sniper Rifles" },
    [19] = { name = "SVD Dragunov", model = "models/weapons/w_svd_dragunov.mdl", entity = "m9k_dragunov", pricesep = 20000, category = "Sniper Rifles" },
    [20] = { name = "PSG-1", model = "models/weapons/w_hk_psg1.mdl", entity = "m9k_psg1", pricesep = 20000, category = "Sniper Rifles" },
    [21] = { name = "SVT 40", model = "models/weapons/w_svt_40.mdl", entity = "m9k_svt40", pricesep = 20000, category = "Sniper Rifles" },
}
for i, v in ipairs(weapons_BlackMarket_Dealer) do
    DarkRP.createShipment(v.name,{
        model = v.model,
        entity = v.entity,
        price = v.pricesep * 12,
        amount = 10,
        separate = true,
        pricesep = v.pricesep,
        noship = false,
        category = v.category,
        allowed = TEAM_BLACKMARKETDEALER,
        sortOrder = i
    })
end
-----------------------------------------------------------
-- Weapons -- Arms Dealer
-----------------------------------------------------------
weapons_Arms_Dealer = {
    -- Pistols
    [1] = { name = "Guardian Mini", model = "models/weapons/guardian/w_pist_p228.mdl", entity = "m9k_guardian", pricesep = 200, category = "Pistols" },
    [2] = { name = "M92 Beretta", model = "models/weapons/w_beretta_m92.mdl", entity = "m9k_m92beretta", pricesep = 500, category = "Pistols" },
    [3] = { name = "Remington 1858", model = "models/weapons/w_remington_1858.mdl", entity = "m9k_remington1858", pricesep = 500, category = "Pistols" },
    [4] = { name = "FNP 45.Cal Advanced", model = "models/weapons/fnp/w_pist_fiveseven.mdl", entity = "m9k_fnp", pricesep = 1000, category = "Pistols" },
    [5] = { name = "Bren Ten 9mm", model = "models/weapons/w_pist_fokkususp.mdl", entity = "m9k_bren_ten", pricesep = 1000, category = "Pistols" },
    [6] = { name = "SIG Sauer P229R", model = "models/weapons/w_sig_229r.mdl", entity = "m9k_sig_p229r", pricesep = 1000, category = "Pistols" },
    [7] = { name = "MR-96", model = "models/weapons/mr96/w_pist_deagle.mdl", entity = "m9k_mr96", pricesep = 1000, category = "Pistols" },
    [8] = { name = "VP-90", model = "models/weapons/vp70/w_pist_glock18.mdl", entity = "m9k_vp90", pricesep = 1000, category = "Pistols" },
    [9] = { name = "P08 Luger", model = "models/weapons/w_luger_p08.mdl", entity = "m9k_luger", pricesep = 1000, category = "Pistols" },
    [10] = { name = "HK45C", model = "models/weapons/w_hk45c.mdl", entity = "m9k_hk45", pricesep = 1000, category = "Pistols" },
    [11] = { name = "HK USP", model = "models/weapons/w_pist_fokkususp.mdl", entity = "m9k_usps_unsilenced", pricesep = 1000, category = "Pistols" },
    [12] = { name = "Colt 1911", model = "models/weapons/s_dmgf_co1911.mdl", entity = "m9k_colt1911", pricesep = 1000, category = "Pistols" },
    [13] = { name = "Colt 1911 Scoped", model = "models/weapons/s_dmgf_co1911.mdl", entity = "m9k_coltscoped", pricesep = 1100, category = "Pistols" },
    [14] = { name = "HK USP Silenced", model = "models/weapons/w_pist_fokkususp.mdl", entity = "m9k_usps", pricesep = 1100, category = "Pistols" },
    [15] = { name = "S&W Model 3 Russian", model = "models/weapons/w_model_3_rus.mdl", entity = "m9k_model3russian", pricesep = 2000, category = "Pistols" },
    [16] = { name = "S&W Model 627", model = "models/weapons/w_sw_model_627.mdl", entity = "m9k_model627", pricesep = 3000, category = "Pistols" },
    [17] = { name = "Colt Python", model = "models/weapons/w_colt_python.mdl", entity = "m9k_coltpython", pricesep = 3000, category = "Pistols" },
    [18] = { name = "Desert Eagle", model = "models/weapons/w_tcom_deagle.mdl", entity = "m9k_deagle", pricesep = 3500, category = "Pistols" },
    [19] = { name = "Glock 18", model = "models/weapons/w_dmg_glock.mdl", entity = "m9k_glock", pricesep = 4000, category = "Pistols" },
    [20] = { name = "S&W Model 500", model = "models/weapons/w_sw_model_500.mdl", entity = "m9k_model500", pricesep = 4000, category = "Pistols" },
    [21] = { name = "TEC-9", model = "models/weapons/w_intratec_tec9.mdl", entity = "m9k_tec9", pricesep = 4000, category = "Pistols" },
    [22] = { name = "Glock 18 Drum Mag", model = "models/weapons/w_dmg_glock.mdl", entity = "m9k_glock18_extclip", pricesep = 7500, category = "Pistols" },
    -- Shotguns
    [23] = { name = "M97 Trench Gun", model = "models/weapons/w_double_barrel_shotgun.mdl", entity = "m9k_dragonsbreath", pricesep = 5500, category = "Shotguns" },
    [24] = { name = "Winchester 1897", model = "models/weapons/w_winchester_1897_trench.mdl", entity = "m9k_1897winchester", pricesep = 5500, category = "Shotguns" },
    [25] = { name = "Winchester 87", model = "models/weapons/w_winchester_1887.mdl", entity = "m9k_1887winchester", pricesep = 5500, category = "Shotguns" },
    [26] = { name = "Ithaca M37", model = "models/weapons/w_ithaca_m37.mdl", entity = "m9k_ithacam37", pricesep = 5500 , category = "Shotguns" },
    [27] = { name = "Mossberg 590", model = "models/weapons/w_mossberg_590.mdl", entity = "m9k_mossberg590", pricesep = 5500, category = "Shotguns" },
    [28] = { name = "Serbu Super Shorty", model = "models/weapons/w_benelli_m3.mdl", entity = "m9k_serbushorty", pricesep = 5500, category = "Shotguns" },
    [29] = { name = "FN TPS", model = "models/weapons/w_ithaca_m37.mdl", entity = "m9k_fntps", pricesep = 7000, category = "Shotguns" },
    [30] = { name = "M3 Tactical", model = "models/weapons/w_benelli_m3.mdl", entity = "m9k_m3tactical", pricesep = 7000, category = "Shotguns" },
    [31] = { name = "Benelli M3", model = "models/weapons/w_benelli_m3.mdl", entity = "m9k_m3", pricesep = 7000, category = "Shotguns" },
    [32] = { name = "Double Barrel Shotgun", model = "models/weapons/w_double_barrel_shotgun.mdl", entity = "m9k_dbarrel", pricesep = 7000, category = "Shotguns" },
    [33] = { name = "Remington 870", model = "models/weapons/w_remington_870_tact.mdl", entity = "m9k_remington870", pricesep = 7000, category = "Shotguns" },
    [34] = { name = "KSG-12", model = "models/weapons/w_ithaca_m37.mdl", entity = "m9k_ksg", pricesep = 7500, category = "Shotguns" },
    [35] = { name = "Baikal MP-153", model = "models/weapons/w_double_barrel_shotgun.mdl", entity = "m9k_baikal", pricesep = 7500, category = "Shotguns" },
    [36] = { name = "Browning Auto 5", model = "models/weapons/w_browning_auto.mdl", entity = "m9k_browningauto5", pricesep = 8500, category = "Shotguns" },
    [37] = { name = "Pancor Jackhammer", model = "models/weapons/w_pancor_jackhammer.mdl", entity = "m9k_jackhammer", pricesep = 8500, category = "Shotguns" },
    [38] = { name = "SPAS 12", model = "models/weapons/w_spas_12.mdl", entity = "m9k_spas12", pricesep = 8500, category = "Shotguns" },
    [39] = { name = "SPAS 12 Closed Stock", model = "models/weapons/w_spas_12.mdl", entity = "m9k_spas12stock", pricesep = 8500, category = "Shotguns" },
    [40] = { name = "SPAS 12 Silenced", model = "models/weapons/w_spas_12.mdl", entity = "m9k_spas12silenced", pricesep = 8500, category = "Shotguns" },
    -- Assault Rifles
    [41] = { name = "73 Winchester Carbine", model = "models/weapons/w_winchester_1873.mdl", entity = "m9k_winchester73", pricesep = 6000, category = "Rifles" },
    [42] = { name = "FN FAL", model = "models/weapons/w_fn_fal.mdl", entity = "m9k_fal", pricesep = 10000, category = "Rifles" },
    [43] = { name = "FN FNC Police", model = "models/weapons/w_fn_fal.mdl", entity = "m9k_fnc", pricesep = 13000, category = "Rifles" },
    [44] = { name = "HK G3A3", model = "models/weapons/w_hk_g3.mdl", entity = "m9k_g3a3", pricesep = 13000, category = "Rifles" },
    [45] = { name = "VZOR 58", model = "models/weapons/w_ak47_m9k.mdl", entity = "m9k_vz58", pricesep = 14000, category = "Rifles" },
    [46] = { name = "Sturmgewehr 44", model = "models/weapons/w_mp40smg.mdl", entity = "m9k_sturmgewehr44", pricesep = 14000, category = "Rifles" },
    [47] = { name = "QBZ-97", model = "models/weapons/w_tct_famas.mdl", entity = "m9k_qbz97", pricesep = 14000, category = "Rifles" },
    [48] = { name = "AK-74", model = "models/weapons/w_tct_ak47.mdl", entity = "m9k_ak74", pricesep = 14000, category = "Rifles" },
    [49] = { name = "AK-47", model = "models/weapons/w_ak47_m9k.mdl", entity = "m9k_ak47", pricesep = 14000, category = "Rifles" },
    [50] = { name = "AK-74U", model = "models/weapons/w_ak47_m9k.mdl", entity = "m9k_ak74u", pricesep = 14000, category = "Rifles" },
    [51] = { name = "AK-47 SD", model = "models/weapons/w_ak47_m9k.mdl", entity = "m9k_ak47sd", pricesep = 14000, category = "Rifles" },
    [52] = { name = "HK 416", model = "models/weapons/w_hk_416.mdl", entity = "m9k_m416", pricesep = 14000, category = "Rifles" },
    [53] = { name = "AS VAL", model = "models/weapons/w_dmg_vally.mdl", entity = "m9k_val", pricesep = 14000, category = "Rifles" },
    [54] = { name = "AN-94", model = "models/weapons/w_rif_an_94.mdl", entity = "m9k_an94", pricesep = 14000, category = "Rifles" },
    [55] = { name = "AMD 65", model = "models/weapons/w_amd_65.mdl", entity = "m9k_amd65", pricesep = 14000, category = "Rifles" },
    [56] = { name = "ACR", model = "models/weapons/w_masada_acr.mdl", entity = "m9k_acr", pricesep = 14000, category = "Rifles" },
    [57] = { name = "G36", model = "models/weapons/w_hk_g36c.mdl", entity = "m9k_g36", pricesep = 14000, category = "Rifles" },
    [58] = { name = "M4A4", model = "models/weapons/w_m4a1_iron.mdl", entity = "m9k_m4a4", pricesep = 14000, category = "Rifles" },
    [59] = { name = "M16A4", model = "models/weapons/w_dmg_m16ag.mdl", entity = "m9k_m16a4", pricesep = 14000, category = "Rifles" },
    [60] = { name = "M4A1 Iron", model = "models/weapons/w_m4a1_iron.mdl", entity = "m9k_m4a1", pricesep = 14000, category = "Rifles" },
    [61] = { name = "M14", model = "models/weapons/w_snip_m14sp.mdl", entity = "m9k_m14sp", pricesep = 10000, category = "Rifles" },
    [62] = { name = "M16A4 ACOG", model = "models/weapons/w_dmg_m16ag.mdl", entity = "m9k_m16a4_acog", pricesep = 15000, category = "Rifles" },
    [63] = { name = "G36 Assault", model = "models/weapons/w_hk_g36c.mdl", entity = "m9k_asg36", pricesep = 15000, category = "Rifles" },
    [64] = { name = "L85", model = "models/weapons/w_l85a2.mdl", entity = "m9k_l85", pricesep = 15000, category = "Rifles" },
    [65] = { name = "FAMAS", model = "models/weapons/w_tct_famas.mdl", entity = "m9k_famas", pricesep = 15000, category = "Rifles" },
    [66] = { name = "F2000", model = "models/weapons/w_fn_f2000.mdl", entity = "m9k_f2000", pricesep = 15000, category = "Rifles" },
    [67] = { name = "KAC PDW", model = "models/weapons/w_kac_pdw.mdl", entity = "m9k_kac_pdw", pricesep = 15000, category = "Rifles" },
    [68] = { name = "HK SL8", model = "models/weapons/w_hk_sl8.mdl", entity = "m9k_sl8", pricesep = 15000, category = "Rifles" },
    [69] = { name = "AAC Honey Badger", model = "models/weapons/w_aac_honeybadger.mdl", entity = "m9k_honeybadger", pricesep = 15000, category = "Rifles" },
    [70] = { name = "FW900K", model = "models/weapons/w_hk_sl8.mdl", entity = "m9k_fw", pricesep = 15000, category = "Rifles" },
    [71] = { name = "TAR-21", model = "models/weapons/w_imi_tar21.mdl", entity = "m9k_tar21", pricesep = 15000, category = "Rifles" },
    [72] = { name = "Steyr AUG A3", model = "models/weapons/w_auga3.mdl", entity = "m9k_auga3", pricesep = 15000, category = "Rifles" },
    [73] = { name = "SR-3M Vikhr", model = "models/weapons/w_dmg_vikhr.mdl", entity = "m9k_vikhr", pricesep = 15000, category = "Rifles" },
    [74] = { name = "SCAR", model = "models/weapons/w_fn_scar_h.mdl", entity = "m9k_scar", pricesep = 15000, category = "Rifles" },
    -- LMGs
    [75] = { name = "FG 42", model = "models/weapons/w_fg42.mdl", entity = "m9k_fg42", pricesep = 18000, category = "Light-Machine Guns" },
    [76] = { name = "M1918 BAR", model = "models/weapons/w_m1918_bar.mdl", entity = "m9k_m1918bar", pricesep = 18000, category = "Light-Machine Guns" },
    [77] = { name = "M60 Machine Gun", model = "models/weapons/w_m60_machine_gun.mdl", entity = "m9k_m60", pricesep = 20000, category = "Light-Machine Guns" },
    -- Sniper Rifles
    [78] = { name = "Thompson Contender G2", model = "models/weapons/w_g2_contender.mdl", entity = "m9k_contender", pricesep = 10000, category = "Sniper Rifles" },
    [79] = { name = "AI AW50", model = "models/weapons/w_acc_int_aw50.mdl", entity = "m9k_aw50", pricesep = 15000, category = "Sniper Rifles" },
    [80] = { name = "Intervention", model = "models/weapons/w_snip_int.mdl", entity = "m9k_intervention", pricesep = 15000, category = "Sniper Rifles" },
    [81] = { name = "M24", model = "models/weapons/w_snip_m24_6.mdl", entity = "m9k_m24", pricesep = 15000, category = "Sniper Rifles" },
    [82] = { name = "Remington 7615P", model = "models/weapons/w_remington_7615p.mdl", entity = "m9k_remington7615p", pricesep = 15000, category = "Sniper Rifles" },
    [83] = { name = "Barret M98B", model = "models/weapons/w_barrett_m98b.mdl", entity = "m9k_m98b", pricesep = 15000, category = "Sniper Rifles" },
    [84] = { name = "Barret M82", model = "models/weapons/w_barret_m82.mdl", entity = "m9k_barret_m82", pricesep = 16000, category = "Sniper Rifles" },
    -- SMGs
    [85] = { name = "Magpul PDR", model = "models/weapons/w_magpul_pdr.mdl", entity = "m9k_magpulpdr", pricesep = 11000, category = "Sub-Machine Guns" },
    [86] = { name = "UZI", model = "models/weapons/w_uzi_imi.mdl", entity = "m9k_uzi", pricesep = 11000, category = "Sub-Machine Guns" },
    [87] = { name = "MP40", model = "models/weapons/w_mp40smg.mdl", entity = "m9k_mp40", pricesep = 11000, category = "Sub-Machine Guns" },
    [88] = { name = "HK MP5", model = "models/weapons/w_hk_mp5.mdl", entity = "m9k_mp5", pricesep = 11000, category = "Sub-Machine Guns" },
    [89] = { name = "HK MP7", model = "models/weapons/w_mp7_silenced.mdl", entity = "m9k_mp7", pricesep = 12000, category = "Sub-Machine Guns" },
    [90] = { name = "MP5SD", model = "models/weapons/w_hk_mp5sd.mdl", entity = "m9k_mp5sd", pricesep = 12000, category = "Sub-Machine Guns" },
    [91] = { name = "HK UMP45", model = "models/weapons/w_hk_ump45.mdl", entity = "m9k_ump45", pricesep = 12000, category = "Sub-Machine Guns" },
    [92] = { name = "HK USC", model = "models/weapons/w_hk_usc.mdl", entity = "m9k_usc", pricesep = 12000, category = "Sub-Machine Guns" },
    [93] = { name = "FN P90", model = "models/weapons/w_fn_p90.mdl", entity = "m9k_smgp90", pricesep = 12000, category = "Sub-Machine Guns" },
    [94] = { name = "STEN", model = "models/weapons/w_sten.mdl", entity = "m9k_sten", pricesep = 12000, category = "Sub-Machine Guns" },
    [95] = { name = "KRISS Vector", model = "models/weapons/w_kriss_vector.mdl", entity = "m9k_vector", pricesep = 13000, category = "Sub-Machine Guns" },
    [96] = { name = "MP9", model = "models/weapons/w_brugger_thomet_mp9.mdl", entity = "m9k_mp9", pricesep = 13000, category = "Sub-Machine Guns" },
    [97] = { name = "Bizon PP19", model = "models/weapons/w_pp19_bizon.mdl", entity = "m9k_bizonp19", pricesep = 13000, category = "Sub-Machine Guns" },
    [98] = { name = "Tommy Gun", model = "models/weapons/w_tommy_gun.mdl", entity = "m9k_thompson", pricesep = 14000, category = "Sub-Machine Guns" },
}

for i, v in ipairs(weapons_Arms_Dealer) do
    DarkRP.createShipment(v.name,{
        model = v.model,
        entity = v.entity,
        price = v.pricesep * 12,
        amount = 10,
        separate = true,
        pricesep = v.pricesep,
        noship = false,
        category = v.category,
        allowed = TEAM_ARMSDEALER,
        sortOrder = i
    })
end